# Generated by Django 3.2.3 on 2021-05-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='test_no',
            field=models.IntegerField(default=0),
        ),
    ]
